git:
  depth: 1

jobs:
  include:
     - stage: build
       os: linux
       dist: xenial
       language: java
       jdk: oraclejdk12
       script:
         - set -e

         - wget http://central.maven.org/maven2/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar -O java/windows/jna.jar
         - wget http://central.maven.org/maven2/net/java/dev/jna/jna-platform/4.5.2/jna-platform-4.5.2.jar -O java/windows/jna-platform.jar

         - cd java/windows
         - cmake -Bbuild -H. -DJNA_PATH:PATH="$(pwd)"
         - cmake --build build

         - set +e
