git:
  depth: 1

jobs:
  include:
     - stage: win32-demo-helper-app -- windows, release, msvc, 32-bit
       os: windows
       language: cpp
       env: BUILD_TYPE="Release"
       script:
         - set -e

         - cd common/windows/win32-demo-helper-app
         - cmake -Bbuild -H. -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE
         - cmake --build build

         - set +e

     - stage: native-window-host, example -- linux, jdk 1.8, 64-bit
       os: linux
       dist: xenial
       language: java
       jdk: openjdk10
       script:
         - set -e

         - wget http://central.maven.org/maven2/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar -O java/windows/jna.jar
         - wget http://central.maven.org/maven2/net/java/dev/jna/jna-platform/4.5.2/jna-platform-4.5.2.jar -O java/windows/jna-platform.jar

         - cd java/windows
         - cmake -Bbuild -H. -DJNA_PATH:PATH="$(pwd)"
         - cmake --build build

         - set +e
