stages:
  - build

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - karelburda89@gmail.com

jobs:
  include:
     - stage: buuld
       dist: trusty
       os: linux
       language: java
       jdk: oraclejdk8
       script:
         - set -e

         - wget http://central.maven.org/maven2/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar -O java/windows/jna.jar
         - wget http://central.maven.org/maven2/net/java/dev/jna/jna-platform/4.5.2/jna-platform-4.5.2.jar -O java/windows/jna-platform.jar
         - pushd java/windows
         - cmake -Bbuild -H. -DJNA_PATH:PATH=$(pwd)
         - cmake --build build
         - cmake --build build --target run-demo

         - set +e
