stages:
  - build

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - karelburda89@gmail.com

jobs:
  include:
     - stage: buuld
       dist: trusty
       os: linux
       language: java
       jdk: oraclejdk8
       addons:
         apt:
           packages:
             - libjna
       script:
         - set -e

         - echo $JAVA_HOME
         - cmake -Bbuild -H.

         - cmake -Bbuild/java -Hjava/windows
         - cmake --build build/java

         - set +e
