stages:
  - build

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - karelburda89@gmail.com

jobs:
  include:
     - stage: buuld
       dist: trusty
       os: linux
       language: java
       jdk: oraclejdk8
       script:
         - set -e

         - echo $JAVA_HOME
         - cmake -Bbuild -H.

         - wget http://central.maven.org/maven2/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar -O java/windows/jna.jar
         - wget http://central.maven.org/maven2/net/java/dev/jna/jna-platform/4.5.2/jna-platform-4.5.2.jar -O java/windows/jna-platform.jar
         - cmake -Bbuild/java -Hjava/windows -DJNA_PATH:STRING=.
         - cmake --build build/java

         - set +e
